### ISSUE TITLE
saving in a cookie that i dont want a cookie

### ISSUE THREAD

**Issue by nattyluke** [promosis/vue-cookie-accept-decline#11]
I dont know if its a problem to save in a cookie that someone doesn't want a cookie.
Maybe you should give a third button "doNothingContent" and a "clicked-nothing" event that just minifies the message and doesnt do anything?
I'm not sure if that is necessary? 
I would like to contribute and add a Button if you like.

**Comment by nattyluke** [comment]
wonderful thank you too

**Comment by johndatserakis** [comment]
Not a stupid question at all! This component does actually use localStorage - but to support older browsers, it does fallback to actual cookies using [tiny-cookie](https://github.com/Alex1990/tiny-cookie#readme) when localStorage is not supported. 

I know it's a bit confusing considering the naming of the component, but the user privacy opt-in concept is the same - the user may want you to store information about them using a "method" (cookie or localStorage) *or* they may not want you to store this information. Hopefully this is a proper answer, thank you!
