### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by JFGHT** [promosis/vue-cookie-accept-decline#14]
After last update I'm having this error:

> This dependency was not found:
> 
> * vue-cookie-accept-decline in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=scri
> pt&lang=ts&
> 
> To install it, you can run: npm install --save vue-cookie-accept-decline

Re installed it and nothing.

**Comment by johndatserakis** [comment]
Darn sorry about that - I broke it when I cleaned some things up yesterday. I just published `5.2.1` which fixes the issue.  Please update you're package.json to `5.2.1`. Sorry again - my bad.

**Comment by JFGHT** [comment]
Thanks for the fast reaction ;).
