### ISSUE TITLE
Cookie banner not loading style/animation in vue3

### ISSUE THREAD

**Issue by alex-plosceac** [promosis/vue-cookie-accept-decline#24]
Hi guys,

I am migrating a pretty big project from Vue2 to Vue3.4.19 and noticed there's an issue with the Cookie banner not showing properly.
This is my implementation. Worth mentioning that the functionality is on point, the only issue is the animation and the design itself

<img width="809" alt="Screenshot 2024-02-19 at 18 53 24" src="https://github.com/johndatserakis/vue-cookie-accept-decline/assets/126476918/e397ecae-d516-4e03-bb41-269a0da38dcf">

Appearance on Vue 2
<img width="628" alt="Screenshot 2024-02-19 at 18 36 23" src="https://github.com/johndatserakis/vue-cookie-accept-decline/assets/126476918/191debf1-72fd-44c2-bb6d-8b686e584260">

Appearance in Vue  3 (I have to find the div in Inspect Element and select Scroll to view to be able to see it)
<img width="556" alt="Screenshot 2024-02-19 at 18 53 08" src="https://github.com/johndatserakis/vue-cookie-accept-decline/assets/126476918/7b457c3c-6c49-411e-8312-d077a846c493">

**Comment by johndatserakis** [comment]
Hi there, hmm right away I'd assume the CSS isn't being loaded. I see you're importing it on line 20, but I'd check to see if your version of Vue 3 has updated the instructions on how to import a library's CSS.

One workaround regardless of what you find would be to copy the [CSS source code](https://unpkg.com/vue-cookie-accept-decline@6.1.0/dist/vue-cookie-accept-decline.css) directly to your project and load it. If you load it at the right scope, the styles should pick up just fine.

Let me know how it goes.

**Comment by alex-plosceac** [comment]
@johndatserakis thanks for the tips. 
I already implemented the workaround after posting the issue, and it does work indeed, but I'd rather get the import to work. 
I'll check Vue's CSS import and hopefully it'll sort things out.

**Comment by johndatserakis** [comment]
Got it. Yea sorry a bit swamped right now, will look into this ASAP.
